server:
  port: 8083
  host: "localhost"
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: passroot
  dbName: dbdev
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  logLevel: debug
  logFilePath: "./storages/logs/log.txt"
  sampling:
    initial: 100
    therehold: 1000
  maxSize: 500 # MB
  maxAge: 30 # days
  maxBackups: 3
  compress: true

